name: Tagged Docker Publish

on:
  push:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Use Custom Dockerfile
        run: |
          rm Dockerfile
          cp .github/Dockerfile .
      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          
      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: ${{ env.GIT_TAG }}
        run: |
          docker build -t trksteam/wfbot::$IMAGE_TAG .
          docker push trksteam/wfbot:$IMAGE_TAG
          
      
